Financial-Times/o-overlay

- demos/src/demo.js
- origami.json
- src/js/overlay.js
- src/scss/_fullscreen.scss
- src/scss/overlay.scss
where content was not being centered properly when opening an overlay imperatively in a smaller screen
Also sets status to active
> Closes issue 31 

- src/scss/_arrow.scss
- src/scss/_cross.scss
- src/scss/_shaded.scss
- src/scss/overlay.scss
See http://sassdoc.com/develop/annotations
http://sassdoc.com/develop/upgrading
> Update documentation to Sassdoc 2.0 syntax

- demos/centered-overlay.html
- demos/modal.html
- demos/overlay-with-arrow.html
- demos/src/centered-overlay.mustache
- demos/src/demo.scss
- demos/src/modal.mustache
- demos/src/overlay-with-arrow.mustache
> Removes wide squat

- src/js/overlay.js
> Fixed getting the width of the overlay and resets arrow classes properly

- README.md
- main.scss
- src/js/overlay.js
> Documented problem with autofocus and strips unecessary sassdoc stuff

- src/js/overlay.js
Trigger o-error events when errors are thrown.
> o-errors integration

- bower.json
- src/js/overlay.js
> dom-delegate -> ftdomdelegate

- src/js/overlay.js
Fixes #88 
Takes into account the height of the border.
> Fix content running off overlay

- src/scss/_cross.scss
Fixes #65 
Also looks more consistent with 10px margin right.
> Align close button

- demos/src/centered-overlay.mustache
- demos/src/modal.mustache
- demos/src/overlay-with-arrow.mustache
- src/js/overlay.js
- test/specs/overlay.test.js
Leaving this here for comment on the solutions for the time being. 
There's some work to do on getting the correct testing set up in other PRs which allow the switch to ES6, so will be doing that first.
Fixes #45,
Fixes #48,  and
Fixes #54
> Accessibility updates

- test/specs/overlay.test.js
Migrating from Akamai to Fastly!
> Update overlay.test.js with new build URL

- karma.conf.js
- src/scss/_cross.scss
- src/scss/_shaded.scss
> Fix the icon cross hover state and shaded states

- bower.json
Widen some semver ranges for dependencies
> bump dependencies

- src/js/overlay.js
- src/scss/_color-use-cases.scss
Allow title property of heading to be optional.
Enable the colour of the close X to be overridden by SASS variable.
> Amend: make title optional and enable cross color override

- karma.conf.js
- package.json
Add istanbul coverage reports.
> Add istanbul coverage

- package.json
- test/helpers/fixtures.js
- test/specs/origami.test.js
Add in the origami tests that check that the thing initialises in the standard way.
> Add core tests

- test/specs/o-overlay.test.js
> adds optional header test

- main.js
- src/js/overlay.js
- src/js/utils.js
- test/helpers/events.js
Reverts Financial-Times/o-overlay#179
> Revert "use ESM insteadof CJS"

- src/js/overlay.js
This is a basic implimentation of focus trapping to improve the
accessibility for keyboard users.
There are possibly way to make this more robust but I think this is a
good starting point as right now we have nothing.
> Trap focus inside the overlay whilst open

- MIGRATION.md
- demos/src/demo.js
- main.js
- src/js/overlay.js
- src/js/utils.js
- test/helpers/events.js
- test/specs/smoke.test.js
> Use ESM over CommonJS

- MIGRATION.md
- src/scss/_mixins.scss
@notlee I don't know whether this will _actually_ fix #204 - possibly
I've misunderstood what the issue is.
> Give the overlay and shadow different a z-index

- MIGRATION.md
- src/js/overlay.js
- test/specs/o-overlay.test.js
> Throw an error if overlay ID is not unique

- MIGRATION.md
- src/js/overlay.js
> Remove deprecated camelCase options

- MIGRATION.md
- bower.json
- demos/src/demo.scss
- demos/src/sliding-notification.scss
- main.scss
- src/scss/_compact.scss
- src/scss/_mixins.scss
This adds in o-typography. I haven't changed any of the spacing values,
as I might investigate using o-spacing for that.
Resolves #176
> Use o-typography for consistent typography styles

- demos/src/demo.js
- demos/src/sliding-notification.js
- src/js/overlay.js
> Remove non-ascii alphanumericals when generating heading id

- README.md
- src/js/overlay.js
I don't know what specific use-case this is for, but:
let's either merge this or decide not to do it and close #168
> Expose overlay on the ready event detail
