- src/js/overlay.js
Fixes the regression mentioned in #73
> Removed preventDefault() that was breaking forms in overlay

- src/js/overlay.js
> #82: IE10 and IE11 does not support classList.remove with multiple parameters

- main.scss
- src/scss/_fullscreen.scss
The overflow:hidden added by the full_width class hides the :before and :after elements (arrows). The overflow:hidden should be added to the content class only.
Fixes #84
> #84: Overlay arrow missing after resize to a screen width less than the width of the overlay

- src/js/overlay.js
- test/specs/smoke-test.js
This enables users of the component to override the default styling of the component using a modifier selector, if they wish too. A use-case we have on Next. 
/cc @AlbertoElias
> Add instance ID as BEM modifier to enable use as a styling hook

- src/js/overlay.js
In Safari adding focus to the overlay wrapper was causing the page to jump to the bottom (see #104). I've moved where the focus is added now to after the wrapper has been displayed to prevent the jump.
Fixes #104
> Move overlay wrapper focus to after overlay is setup

- main.scss
- src/js/overlay.js
- src/scss/_cross.scss
This commit replaces the CSS cross for the close button with one from o-icons.
This commit does not introduce a dependency on o-icons, rather it gets the cross
from the image service. This is so that this change doesn't have to be a
breaking change, and so that this version can remain compatible with older
versions of components which use older versions of o-[ft]-icons (because they
use the icon font still)
Some future work should be done to use the mixin provided by o-icons to set the
background image of the close button instead of doing it directly in the Sass here.
This commit:
- Removes the internal span (o-overlay__close-icon) from the close button as
it's no longer needed
- Adds a background image to the overlay
> Replace CSS cross with o-icons cross.

- README.md
- demos/src/modal-prevent-closure.mustache
- origami.json
- src/js/overlay.js
- test/specs/overlay.test.js
cc: @onishiweb 
For ad-blocking we will want to have a modal overlay that can not be closed, forcing the user to take an action specified in the html.
The objective of this PR is to handle an option (`preventclosing`), that is only compatible with modal overlays.
It suppresses the header close function (eg. the `x`) as well as the escape click to close.
Have added a test to prove that preventclosing works.
> Add: option to prevent closing

- README.md
- src/js/overlay.js
@onishiweb 
Adam,
Was thinking through how best to achieve the ability to have a close button without a header & title.
Simplest seems to be this;
- Create a customised close button in the html for the overlay that I pass through to o-overlay (using the o-overlay__close class on it)
- Pass a `customclose=true` option through so that it then puts the right close handling functionality onto it.
This causes no disruption to any existing use cases, but gives the flexibility that I'm looking for.
> Amend: Allow custom close in overlay html

- src/scss/_color-use-cases.scss
Was in previously reverted change.
Maintains existing color as default with opportunity to pass in different color as a variable.
> Add: variable for close button color

- README.md
- demos/src/sliding-notification.js
- demos/src/sliding-notification.mustache
- demos/src/sliding-notification.scss
- origami.json
- src/js/overlay.js
This commit adds new config options:
- Title.visuallyHideTitle: Boolean. Prevent the overlay title from being added to the overlay (except for the aria markup)
- nested: Boolean - this will remove all of the positioning and
repositioning logic. This will allow the user to handle that behaviour
themselves
- parentNode: Should be a selector for the parent element to append the
overlay to. When used with `nested: true` this option can be used to
position the overlay somewhere other than in the middle of the page or
relative to a target (the other two options currently supported)
O-overlay is due some TLC which will happen as part of the next major. The key thing with this PR is that it doesn't break any existing implementations and allows @aendrew to get on with his bootcamp in next!
> Add handling for containers / custom titles

- README.md
- src/js/overlay.js
The tabindex=0 on various elements causes weird behaviours when using the `parentNode` and `nested` options, particularly when animating. 
This PR adds a `noFocus` option that disables the `tabindex` attribute setters when `true`. It defaults to `false` so is backwards compatible.
> ✨ Adds noFocus option to prevent tabindex from being set

- README.md
- demos/src/sliding-notification.js
- src/js/overlay.js
- test/specs/o-overlay.test.js
- test/specs/smoke.test.js
Overlays support nested mode within a page, but had some behaviours which only really made sense when they're not nested:
- Nested overlays closed when the escape key was pressed
- Nested overlays closed when a new `layer` was opened
- Nested overlays sent a new `layer` event on creation, closing other layers
I think this is unintended behaviour, preventing the use of multiple nested overlays... this PR treats those behaviours as bugs and prevents them.  Thoughts?
Creation of a testcase also highlighted that some of the more recent properties (`parentNode` and `noFocus`) couldn't be set from attributes, as they're camelCase but get lowercased when plucking from the attribute.  I've changed them all to lowercase to match the older properties but converted the old option names so this …
> Reduce overlay behaviour for nested overlays, allow more properties to be set via attributes

- test/specs/smoke.test.js
Remove the use of an arrow function where `this` is used.
> Remove the use of an arrow function

- README.md
- demos/src/modal-fullscreen.mustache
- demos/src/modal.mustache
- main.scss
- origami.json
- src/js/overlay.js
- src/scss/_fullscreen.scss
- test/specs/o-overlay.test.js
Full screen option:
- Full screen modals are easy to confuse for pages: Back button exits the modal in supported browsers.
- Disables scrolling on the document behind the modal.
- Removes the modal border when full screen.
Class option:
- Enables a client to provide class names to add to the generated overlay wrapper. This allows a client to easily provide custom CSS to an individual instance of an overlay.
This is to support a mobile share interface: https://github.com/Financial-Times/o-overlay/issues/143
> Adds a full screen and class option to modals.

- README.md
- origami.json
- src/js/overlay.js
- test/specs/o-overlay.test.js
Clients sometimes change the content of the overlay after it is opened. In these cases the overlay can be mispositioned, and if the content of the overlay becomes larger than the viewport the content is inaccessible as it cannot be scrolled. Calling `realign` after overlay content has updated should correct this.
- Updates `origami.json` demo syntax to conform to the spec.
- Updates the `realign` method so its arguments are optional.
- Corrects some code documentation.
- Surfaces the `realign` method in the README.
> Update `realign` so its arguments are optional.

- src/js/overlay.js
- test/specs/o-overlay.test.js
Prevents accidental overlay closing with multiple fullscreen overlays with the `layer` option set to true (default).
Also warn if an overlay is created with an existing ID, we can't error to prevent this without potentially creating a breaking change.
> Only close the overlay on popstate if the overlay is in history.

- demos/src/demo.scss
- origami.json
- src/scss/_brand.scss
The demo should include o-typography in the future: https://github.com/Financial-Times/o-overlay/issues/176
> Add whitelabel brand support.

- bower.json
- main.scss
- origami.json
- src/scss/_shaded.scss
~As the close button is styled the same when focused or hovered there's no need for `o-hoverable` or `@media (hover)`.~
~Swaps `o-hoverable`  for the native [hover media query](https://drafts.csswg.org/mediaqueries-4/#hover). Removing so we can deprecate o-hoverable: https://github.com/Financial-Times/o-hoverable/issues/29~
Removes `o-hoverable`. The close button is immediately hidden on tap so there's no reason to hide the hover state for primarily touch based devices.
> Remove o-hoverable.

- origami.json
- src/js/overlay.js
The feedback component made us aware of times when the focus trap might
not work because of hidden elements tracked. This could cause the last
focusable element to never get focus.
This improvement means that it will only find elements that are visible
and not disabled.
> Only trap focus on visible and active elements

- origami.json
- src/js/overlay.js
Visibility:
Inputs for radio and checkboxes are visually hidden, so check
the label visibility of inputs too when determining whether to
trap focus.
Radios:
When tabbing, the checked radio input of a group of radio inputs
is focused. To change the radio selection / focus the arrow keys
are used. Tabbing again takes focus to the next focusable element
after the radio group. Therefore focus must be trapped before
radio inputs which are not checked (as they do not receive
focus by tabbing).
> Trap focus of overlays which end with form inputs.

- README.md
- demos/src/sliding-notification.js
- src/js/overlay.js
- Deprecates `visuallyHideTitle` config.
- Supports visually hiding the overlay heading declarative.
Details: https://github.com/Financial-Times/o-overlay/issues/199
> Update option "visuallyHideTitle" to "visuallyhide".

- src/js/overlay.js
Just for consistency with more recent components.
⚠️ **[PROBABLY BEST TO VIEW WITH WHITESPACE CHANGES IGNORED](https://github.com/Financial-Times/o-overlay/pull/215/files?w=1)** ⚠️
> Switch to using a class rather than prototypes

- src/js/overlay.js
The regex used when assigning a headingId value can currently only copy with a single whitespace.
For any value with more than one whitespace, this is the result (`Copy to list` gets turned into `copy-to list`, with the additional whitespace persisting):
This PR ensures that the regex will convert all whitespace to hyphens.
> Fix headingId value assignment regex

- test/specs/o-overlay.test.js
- test/specs/origami.test.js
- test/specs/smoke.test.js
Stop using the magic imports for proclaim and sinon and pull them from the global because that's where Karma has added them. This is required for obt v10 to be released.
> Stop using magic webpack imports

- demos/src/sliding-notification.js
- main.js
- src/js/overlay.js
- test/specs/o-overlay.test.js
- test/specs/origami.test.js
- test/specs/smoke.test.js
relative imports require the full path including the extension because browsers use the import name to make a network request and they do not implicitly add a .js file extension if one is missing
> add extension to relative imports to make the code work directly in a browser
